// Code generated by goctl. DO NOT EDIT.
package types


type MessageInfo struct {
	Content  string `json:"content"`
	From     int64  `json:"from"`
	To       int64  `json:"to"`
	SendTime string `json:"send_time"`
}

type User struct {
	Id        int64          `json:"id"`
	Name      string         `json:"name"`
}