// Code generated by goctl. DO NOT EDIT.
package types

type AllUserReq struct {
}

type AllUserResp struct {
	Users []UserEntity `json:"users"`
}

type FindUserByIDReq struct {
	Id string `json:"id"`
}

type FindUserByIDResp struct {
	Users []UserEntity `json:"users"`
}

type FindUserByNameReq struct {
	Name string `json:"name"`
}

type FindUserByNameResp struct {
	Users []UserEntity `json:"users"`
}

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type UserEntity struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
