// Code generated by goctl. DO NOT EDIT.
package types

type AllUserReq struct {
}

type AllUserResp struct {
	Users []UserEntity `json:"users"`
}

type FindFriendReq struct {
	Id int64 `json:"id"` // 将 Id 类型改为 int64
}

type FindFriendResp struct {
	Users []UserEntity `json:"users"`
}

type FindUserReq struct {
	Name string `json:"name"`
	Id   int64  `json:"id"` // 将 Id 类型改为 int64
}

type FindUserResp struct {
	Users []UserEntity `json:"users"`
}

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type UserEntity struct {
	Id   int64  `json:"id"` // 将 Id 类型改为 int64
	Name string `json:"name"`
}
