// Code generated by goctl. DO NOT EDIT.
package types

type GetAllGroupByUserIdRequest struct {
}

type GetAllGroupByUserIdResponse struct {
	Groups []int64 `json:"groups"`
}

type JoinGroupRequest struct {
	GroupId int64 `path:"groupid"`
}

type JoinGroupResponse struct {
	Response string `json:"response"`
}

type MessageInfo struct {
	Content  string `json:"content"`
	From     int64  `json:"from"`
	To       int64  `json:"to"`
	Type     int64  `json:"type"`
	SendTime string `json:"send_time"`
}

type QuitGroupRequest struct {
	Uid int64 `json:"uid"`
	Gid int64 `json:"gid"`
}

type QuitGroupResponse struct {
	Response string `json:"response"`
}

type RecordListRequest struct {
	GroupId int64 `path:"groupid"`
}

type RecordListResponse struct {
	RecordList []MessageInfo `json:"recodelist"`
}
