// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"ZChat/apps/group-chat/internal/handler/chatconn"
	"net/http"

	"ZChat/apps/group-chat/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chatconn",
				Handler: chatconn.ChatConnHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/groupchat"),
	)
}
