// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"ZeZeIM/user/rpc/internal/logic"
	"ZeZeIM/user/rpc/internal/svc"
	"ZeZeIM/user/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb_user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *pb_user.UserRequest) (*pb_user.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
